ifndef::env-github[:icons: font]
:toc: preamble
:toclevels: 2
:sectanchors:

ifdef::env-github[]
++++
<a id="readme-top"></a>
<div align="center">
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/graphs/contributors"><img src="https://img.shields.io/github/contributors/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge" alt="Contributors"></a>
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/network/members"><img src="https://img.shields.io/github/forks/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge" alt="Forks"></a>
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/stargazers"><img src="https://img.shields.io/github/stars/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge" alt="Stars"></a>
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/issues"><img src="https://img.shields.io/github/issues/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge" alt="Issues"></a>
<br />
<h3 align="center">CrystalDiskMark D</h3>
<p align="center">
CrystalDiskMark rewrite in Dlang.<br />
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/issues">Report Bug</a>
&middot;
<a href="https://github.com/AMDphreak/crystaldiskmark-dlang/issues">Request Feature</a>
</p>
</div>
++++
endif::[]

ifndef::env-github[]
image:https://img.shields.io/github/contributors/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge[Contributors,link=https://github.com/AMDphreak/crystaldiskmark-dlang/graphs/contributors]
image:https://img.shields.io/github/forks/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge[Forks,link=https://github.com/AMDphreak/crystaldiskmark-dlang/network/members]
image:https://img.shields.io/github/stars/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge[Stars,link=https://github.com/AMDphreak/crystaldiskmark-dlang/stargazers]
image:https://img.shields.io/github/issues/AMDphreak/crystaldiskmark-dlang.svg?style=for-the-badge[Issues,link=https://github.com/AMDphreak/crystaldiskmark-dlang/issues]

= CrystalDiskMark D

CrystalDiskMark rewrite in Dlang.

link:https://github.com/AMDphreak/crystaldiskmark-dlang/issues[Report Bug] ·
link:https://github.com/AMDphreak/crystaldiskmark-dlang/issues[Request Feature]
endif::[]


== About The Project

A remake of the legendary CrystalDiskMark in Dlang, using dlangui for a modern, intuitive interface.

link:#readme-top[back to top]

== Features

* [ ] Modern UI with common design metaphors
* [ ] Sequential Read/Write benchmarks
* [ ] Random 4K Read/Write benchmarks
* [ ] Support for multiple drives
* [ ] Dark mode support
* [ ] Native Dlang implementation of benchmarks

link:#readme-top[back to top]

== Installation

=== Requirements

* https://dlang.org/download.html[D compiler (DMD/LDC)]
* https://dub.pm/[DUB package manager]

=== Build

[source,powershell]
----
dub build
----

link:#readme-top[back to top]

== Usage

=== Implementation Details

This project aims to replicate the core functionality of CrystalDiskMark while providing a more flexible and modern user experience. It follows the benchmarking methodology documented in the original CrystalDiskMark source.

==== Benchmarking Methodology

Large sequential I/O tests are performed using `CreateFile` with `FILE_FLAG_NO_BUFFERING` and `FILE_FLAG_SEQUENTIAL_SCAN`. Random 4K tests use `FILE_FLAG_RANDOM_ACCESS` and overlapped I/O for high queue depths.

link:#readme-top[back to top]

== License

MIT License — see the original CrystalDiskMark for details.

link:#readme-top[back to top]

== Contact

Ryan Johnson — link:https://twitter.com/amdphreak[@amdphreak]

* Project: https://github.com/AMDphreak/crystaldiskmark-dlang
* Site: https://ryanjohnson.dev

link:#readme-top[back to top]
